name: trackless_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  uuid: ^3.0.6
